https://adventofcode.com/2020/day/10

--- Day 10: Adapter Array ---

Patched into the aircraft's data port, you discover weather forecasts of a massive tropical storm. Before you can figure out whether it will impact your vacation plans, however, your device suddenly turns off!

Its battery is dead.

You'll need to plug it in. There's only one problem: the charging outlet near your seat produces the wrong number of jolts. Always prepared, you make a list of all of the joltage adapters in your bag.

Each of your joltage adapters is rated for a specific output joltage (your puzzle input). Any given adapter can take an input 1, 2, or 3 jolts lower than its rating and still produce its rated output joltage.

In addition, your device has a built-in joltage adapter rated for 3 jolts higher than the highest-rated adapter in your bag. (If your adapter list were 3, 9, and 6, your device's built-in adapter would be rated for 12 jolts.)

Treat the charging outlet near your seat as having an effective joltage rating of 0.

Since you have some time to kill, you might as well test all of your adapters. Wouldn't want to get to your resort and realize you can't even charge your device!

If you use every adapter in your bag at once, what is the distribution of joltage differences between the charging outlet, the adapters, and your device?

For example, suppose that in your bag, you have adapters with the following joltage ratings:

16
10
15
5
1
11
7
19
6
12
4

With these adapters, your device's built-in joltage adapter would be rated for 19 + 3 = 22 jolts, 3 higher than the highest-rated adapter.

Because adapters can only connect to a source 1-3 jolts lower than its rating, in order to use every adapter, you'd need to choose them like this:

    The charging outlet has an effective rating of 0 jolts, so the only adapters that could connect to it directly would need to have a joltage rating of 1, 2, or 3 jolts. Of these, only one you have is an adapter rated 1 jolt (difference of 1).
    From your 1-jolt rated adapter, the only choice is your 4-jolt rated adapter (difference of 3).
    From the 4-jolt rated adapter, the adapters rated 5, 6, or 7 are valid choices. However, in order to not skip any adapters, you have to pick the adapter rated 5 jolts (difference of 1).
    Similarly, the next choices would need to be the adapter rated 6 and then the adapter rated 7 (with difference of 1 and 1).
    The only adapter that works with the 7-jolt rated adapter is the one rated 10 jolts (difference of 3).
    From 10, the choices are 11 or 12; choose 11 (difference of 1) and then 12 (difference of 1).
    After 12, only valid adapter has a rating of 15 (difference of 3), then 16 (difference of 1), then 19 (difference of 3).
    Finally, your device's built-in adapter is always 3 higher than the highest adapter, so its rating is 22 jolts (always a difference of 3).

In this example, when using every adapter, there are 7 differences of 1 jolt and 5 differences of 3 jolts.

Here is a larger example:

28
33
18
42
31
14
46
20
48
47
24
23
49
45
19
38
39
11
1
32
25
35
8
17
7
9
4
2
34
10
3

In this larger example, in a chain that uses all of the adapters, there are 22 differences of 1 jolt and 10 differences of 3 jolts.

Find a chain that uses all of your adapters to connect the charging outlet to your device's built-in adapter and count the joltage differences between the charging outlet, the adapters, and your device. What is the number of 1-jolt differences multiplied by the number of 3-jolt differences?


In [1]:
from collections import Counter

In [2]:
test_list = [16,10, 15, 5, 1, 11, 7, 19, 6, 12, 4]
test_list.append(0)
sorted_test_list = sorted(test_list)
device_jolt_adapter = max(sorted_test_list)+3
sorted_test_list.append(device_jolt_adapter)
jolt_dist = Counter()
for a_idx, a in enumerate(sorted_test_list):
    if a_idx + 1 < len(sorted_test_list):
#         print(a)
        jolt_dist[sorted_test_list[a_idx+1]-a]+=1
jolt_dist

Counter({1: 7, 3: 5})

In [3]:
# Test Case 2
test_list =['28', '33', '18', '42','31', '14', '46', '20', '48', '47', '24', '23', '49', '45', '19', '38', '39', '11', '1', '32', '25', '35', '8', '17', '7', '9', '4','2', '34', '10', '3']
test_list = [int(x) for x in test_list]

#Add 0 -plug in and max+3 - device
test_list.append(0)
sorted_test_list = sorted(test_list)
device_jolt_adapter = max(sorted_test_list)+3
sorted_test_list.append(device_jolt_adapter)

jolt_dist = Counter()
for a_idx, a in enumerate(sorted_test_list):
    if a_idx + 1 < len(sorted_test_list):
        jolt_dist[sorted_test_list[a_idx+1]-a]+=1
jolt_dist

Counter({1: 22, 3: 10})

In [4]:
### PART 1

In [5]:
with open('./data/day10_input.txt', 'r',newline="\n") as reader:
    jolts = reader.readlines()
jolts=[int(x) for x in jolts]
jolts[1:5]

#Add 0 -plug in and max+3 - device
jolts.append(0)
jolts = sorted(jolts)
device_jolt_adapter = max(jolts)+3
jolts.append(device_jolt_adapter)

jolt_dist = Counter()
for a_idx, a in enumerate(jolts):
    if a_idx + 1 < len(jolts):
        jolt_dist[jolts[a_idx+1]-a]+=1
print(f"Resulting Distribution",jolt_dist)
print(f"1-Jolt Diff * 3-Jolt Diff: {jolt_dist[1] * jolt_dist[3]}")

Resulting Distribution Counter({1: 75, 3: 32})
1-Jolt Diff * 3-Jolt Diff: 2400


#### PART 2

To completely determine whether you have enough adapters, you'll need to figure out how many different ways they can be arranged. Every arrangement needs to connect the charging outlet to your device. The previous rules about when adapters can successfully connect still apply.

The first example above (the one that starts with 16, 10, 15) supports the following arrangements:

```
(0), 1, 4, 5, 6, 7, 10, 11, 12, 15, 16, 19, (22)
(0), 1, 4, 5, 6, 7, 10, 12, 15, 16, 19, (22)
(0), 1, 4, 5, 7, 10, 11, 12, 15, 16, 19, (22)
(0), 1, 4, 5, 7, 10, 12, 15, 16, 19, (22)
(0), 1, 4, 6, 7, 10, 11, 12, 15, 16, 19, (22)
(0), 1, 4, 6, 7, 10, 12, 15, 16, 19, (22)
(0), 1, 4, 7, 10, 11, 12, 15, 16, 19, (22)
(0), 1, 4, 7, 10, 12, 15, 16, 19, (22)```

You can make 8 combinations with these

In [6]:
from itertools import combinations

In [7]:
test_list = [16,10, 15, 5, 1, 11, 7, 19, 6, 12, 4]
# test_list.append(0)

## Convert to numpy, add max device num at end (though I dont know if that's 
# necessary since it's always 3 more than max) - I think i can leave it commented out
test_array = np.array(test_list)
# test_array=np.append(test_array,test_array.max()+3)

#Sort list of adapters
test_array.sort()

## This one I found help on - I am looking to split the adapter 
#list to make groupings where there are consecutive ones. Luckily np.split can do this pretty easily
one_groupings = np.split(test_array,np.where(np.diff(test_array) != 1)[0]+1)

#Filter out groupings that are only 1 number (numbers that are 3 more than prev and 3 less than next)
one_groupings = [x for x in one_groupings if len(x)>1]
possible_path_ct = 1
#Loop through all of these groupings
for possible_paths in one_groupings:
    print(possible_paths)
    #create storage list for paths within this that work
    intra_path_groups = list()
    #Loop through all possible lengths of combinations
    for i in range(2,len(possible_paths)+1):
        #loop through all combinations of that length
        for p in list(combinations(possible_paths,i)):
            #if combination is 2 or more, and has group min and max as start and finish, it should be good
            if len(p)>=2 and p[0]==possible_paths.min() and p[-1]==possible_paths.max():
                intra_path_groups.append(p)
    print("\t",intra_path_groups)
    possible_path_ct*=len(intra_path_groups)
    print("**"*30)
print(f"For this case, num possible paths={possible_path_ct}")

[4 5 6 7]
	 [(4, 7), (4, 5, 7), (4, 6, 7), (4, 5, 6, 7)]
************************************************************
[10 11 12]
	 [(10, 12), (10, 11, 12)]
************************************************************
[15 16]
	 [(15, 16)]
************************************************************
For this case, num possible paths=8


In [8]:
a = np.array([45, 49,50])
c = np.diff(a)>3
print(c)
c.any()

[ True False]


True

In [9]:
### TEST CASE 2, PART 2
# Test Case 2
test_list =[28,33,18,42,31,14,46,20,48,47,24,23,49,45,19,38,39,11,1,32,25,35,8,17,7,9,4,2,34,10,3]
test_list = [int(x) for x in test_list]
test_list.append(0)
test_list.append(max(test_list)+3)


## Convert to numpy, add max device num at end (though I dont know if that's 
# necessary since it's always 3 more than max) - I think i can leave it commented out
test_array = np.array(test_list)
# test_array=np.append(test_array,test_array.max()+3)

#Sort list of adapters
test_array.sort()
print(test_array)
print()

## This one I found help on - I am looking to split the adapter 
#list to make groupings where there are consecutive ones. Luckily np.split can do this pretty easily
one_groupings = np.split(test_array,np.where(np.diff(test_array) != 1)[0]+1)

#Filter out groupings that are only 1 number (numbers that are 3 more than prev and 3 less than next)
one_groupings = [x for x in one_groupings if len(x)>1]
possible_path_ct = 1
#Loop through all of these groupings
for possible_paths in one_groupings:
    print(possible_paths)
    #create storage list for paths within this that work
    intra_path_groups = list()
    #Loop through all possible lengths of combinations
    for i in range(len(possible_paths)+1):
        #loop through all combinations of that length
        for p in list(combinations(possible_paths,i)):
            #Remove any with distances of > 3
            c = np.diff(p)<=3
#             print(p,c)
            #if no distances of more than 3, 
            # and combination is 2 or more, and has group min and max as start and finish, it should be good
            if c.all() and len(p)>=2 \
            and p[0]==possible_paths.min() and p[-1]==possible_paths.max():
                intra_path_groups.append(p)
    print("\t",len(intra_path_groups),"|||||",intra_path_groups)
    possible_path_ct*=len(intra_path_groups)
    print(f"Possible Paths up to this point: {possible_path_ct}")
    
    print("**"*30)
print(f"For this case, num possible paths={possible_path_ct}")

[ 0  1  2  3  4  7  8  9 10 11 14 17 18 19 20 23 24 25 28 31 32 33 34 35
 38 39 42 45 46 47 48 49 52]

[0 1 2 3 4]
	 7 ||||| [(0, 1, 4), (0, 2, 4), (0, 3, 4), (0, 1, 2, 4), (0, 1, 3, 4), (0, 2, 3, 4), (0, 1, 2, 3, 4)]
Possible Paths up to this point: 7
************************************************************
[ 7  8  9 10 11]
	 7 ||||| [(7, 8, 11), (7, 9, 11), (7, 10, 11), (7, 8, 9, 11), (7, 8, 10, 11), (7, 9, 10, 11), (7, 8, 9, 10, 11)]
Possible Paths up to this point: 49
************************************************************
[17 18 19 20]
	 4 ||||| [(17, 20), (17, 18, 20), (17, 19, 20), (17, 18, 19, 20)]
Possible Paths up to this point: 196
************************************************************
[23 24 25]
	 2 ||||| [(23, 25), (23, 24, 25)]
Possible Paths up to this point: 392
************************************************************
[31 32 33 34 35]
	 7 ||||| [(31, 32, 35), (31, 33, 35), (31, 34, 35), (31, 32, 33, 35), (31, 32, 34, 35), (31, 33, 34, 35), (31, 32, 33

In [10]:
## PART 2
def part_2(inp_list):
    inp_list = [int(x) for x in inp_list]
    #add input val
    inp_list.append(0)
    #add device adapter
    inp_list.append(max(inp_list)+3)


    ## Convert to numpy, add max device num at end (though I dont know if that's 
    # necessary since it's always 3 more than max) - I think i can leave it commented out
    inp_list = np.array(inp_list)
    # test_array=np.append(test_array,test_array.max()+3)

    #Sort list of adapters
    inp_list.sort()

    ## This one I found help on - I am looking to split the adapter 
    #list to make groupings where there are consecutive ones. Luckily np.split can do this pretty easily
    one_groupings = np.split(inp_list,np.where(np.diff(inp_list) != 1)[0]+1)

    #Filter out groupings that are only 1 number (numbers that are 3 more than prev and 3 less than next)
    one_groupings = [x for x in one_groupings if len(x)>1]
    possible_path_ct = 1
    #Loop through all of these groupings
    for possible_paths in one_groupings:
#         print(possible_paths)
        #create storage list for paths within this that work
        intra_path_groups = list()
        #Loop through all possible lengths of combinations
        for i in range(len(possible_paths)+1):
            #loop through all combinations of that length
            for p in list(combinations(possible_paths,i)):
                #Remove any with distances of > 3
                c = np.diff(p)<=3

                #if no distances of more than 3, 
                # and combination is 2 or more, and has group min and max as start and finish, it should be good
                if c.all() and len(p)>=2 \
                and p[0]==possible_paths.min() and p[-1]==possible_paths.max():
                    intra_path_groups.append(p)

        possible_path_ct*=len(intra_path_groups)
    return possible_path_ct

In [11]:
print(jolts)

[0, 1, 2, 3, 4, 7, 8, 9, 10, 13, 14, 15, 16, 19, 20, 21, 22, 25, 26, 27, 28, 31, 32, 33, 34, 35, 38, 39, 40, 41, 42, 45, 48, 51, 52, 53, 54, 55, 58, 59, 60, 63, 64, 65, 66, 69, 70, 71, 74, 75, 76, 77, 78, 81, 84, 85, 86, 87, 88, 91, 92, 95, 96, 97, 98, 99, 102, 105, 106, 107, 110, 111, 112, 113, 116, 119, 122, 123, 124, 125, 126, 129, 132, 133, 134, 135, 138, 139, 140, 141, 144, 145, 146, 149, 150, 151, 154, 155, 156, 157, 160, 161, 164, 165, 166, 167, 168, 171]


In [12]:
part_2(jolts)

338510590509056

That is right. Woo. That was a tough one